### ISSUE TITLE
Ui title update

### ISSUE THREAD

**Issue by TheItalianAce** [pythoninoffice/amd_webui#1]
the word in the title of the ui should be STABLE not SATBLE

**Comment by TheItalianAce** [comment]
change->
def start_app():
    with gr.Blocks() as app:
        gr.Markdown('SATBLE DIFFUSION WEBUI FOR AMD')
in->
def start_app():
    with gr.Blocks() as app:
        gr.Markdown('STABLE DIFFUSION WEBUI FOR AMD')

**Comment by pythoninoffice** [comment]
Thanks updated! [9451179](https://github.com/pythoninoffice/amd_webui/commit/9451179d83d6630effb753ae8f9de1e8fc71d524)
